### ISSUE TITLE
App crashes after login attempt 

### ISSUE THREAD

**Issue by b3il0** [D4rK7355608/com.google.android.apps.bard#2]
Hey, the app crashes when I try to log into my Google account. This happens with the latest build. 

https://github.com/D4rK7355608/com.google.android.apps.bard/assets/37301674/0c95934d-91b0-4f39-9f8e-9e992305386a

**Comment by MihaiCristianCondrea** [comment]
I have installed the Bard app as well and tried to login but I don't have any crash on my device. Can you share some logs? 🤔

**Comment by b3il0** [comment]
I have never created a log before. Is it this?

`2023-10-07 18:08:30.815 23596 23596 com.conena.logcat.reader E chromium : [ERROR:aw_browser_terminator.cc(156)] Renderer process (25561) crash detected (code -1).`

**Comment by MihaiCristianCondrea** [comment]
I can't help you without more information. The stack trace or logcat you provided doesn't point to the root cause of the problem. I'm releasing a new build soon that will fix the build CI and may also fix your problem.

**Comment by b3il0** [comment]
Thanks. Unfortunately the new version didn't fix it. I use a Logcat app and it doesn't show anything unusual. Bummer.

**Comment by dylanneve1** [comment]
Hey. Exact same issue here. Running Android 14 QPR1 beta Pixel 7, will try take a proper log

**Comment by NielSync** [comment]
Here a crash log @D4rK7355608 
```
FATAL EXCEPTION: main
Process: com.google.android.apps.bard, PID: 28346
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:742)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2690)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3202)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2795)
```

**Comment by khaledmoayad** [comment]
I'm having the same problem, not really sure how to get a log tho

**Comment by b3il0** [comment]
@khaledmoayad maybe check out this one, because that worked for me: 

https://github.com/nayemahmedniloy/Bard/tree/Version_1.0.0(RN)

**Comment by dsssok** [comment]
Unable to run, close the program directly

**Comment by nubesurrealista** [comment]
I'm having the same problem on Android 8.1

**Comment by nubesurrealista** [comment]
Here my log:

FATAL EXCEPTION: main
Process: com.google.android.apps.bard, PID: 13488
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:742)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:765)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2530)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2631)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2631)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2631)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2631)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3035)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2631)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:552)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3327)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)
	at android.view.View.dispatchPointerEvent(View.java:12052)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5064)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4799)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4466)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4523)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7025)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6999)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6956)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7143)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by tz-shuhag** [comment]
having the same issue. The app crashes as I try to log in.

**Comment by jenny850113** [comment]
having the same problem in Samsung S23 (android 13):

 com.google.android.apps.bard         E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.android.apps.bard, PID: 31589
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
                                                                                                    	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:741)
                                                                                                    	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:764)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2846)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3324)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2939)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:776)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1967)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4531)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:734)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:16476)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8482)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8233)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7562)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7619)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7585)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7788)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7593)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7845)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7566)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7619)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7585)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7593)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7566)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:11103)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10985)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10941)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:11237)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:296)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:187)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by tz-shuhag** [comment]
@D4rK7355608  any solution ??

**Comment by EliasGabr** [comment]
same bug i have 😢

**Comment by EliasGabr** [comment]
[dffee.txt](https://github.com/D4rK7355608/com.google.android.apps.bard/files/14214562/dffee.txt)


here is logcat
